sudo: false
language: android
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
dist: trusty
env:
  global:
   - ANDROID_API_LEVEL=29
   - EMULATOR_API_LEVEL=29
   - ANDROID_BUILD_TOOLS_VERSION=29.0.2
   - ANDROID_ABI=google_apis/armeabi-v7a
   - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)
android:
    - tools
    - platform-tools
    - extra
    - add-on
    
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    
    - android-$ANDROID_API_LEVEL
    - android-$EMULATOR_API_LEVEL
    
    - extra-google-google_play_services
    
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    
    - addon-google_apis-google-$ANDROID_API_LEVEL
    - addon-google_apis-google-$EMULATOR_API_LEVEL

    - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
    
before_script:
    - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
